# my-react-app/values.yaml

global:
  system: mwstack-fittracker-backend
deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/fittracker-backend
    tag: 20260228-173810-b310941
  service:
    name: fittracker-backend
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: fittracker-backend.mw.local
    path: /
    tls:
      enable: true
  appconfig:
    db_host: postgres-service.postgres.svc.cluster.local
    db_name: FitTracker
    enable_otel: true
    host: 0.0.0.0
