# my-react-app/values.yaml

deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/mwstack-authenticator
    tag: 20260227-213154-5629544
    pullPolicy: IfNotPresent
  service:
    name: mwstack-authenticator-frontend
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    pathType: ImplementationSpecific
    host: authenticator.mw.local
    path: /

  appconfig:
    host: 0.0.0.0
    port: 8000

    db_host: 192.168.0.11 #localhost
    db_port: 5432
    db_name: MWStackUsers
    db_user: postgres
    db_password: postgres

    enable_otel: false