# my-react-app/values.yaml

global:
  name: mwstack-authenticator
deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/mwstack-authenticator
    tag: 20260301-131214-9b0da5e
    pullPolicy: IfNotPresent
  service:
    name: mwstack-authenticator-frontend
    targetPort: 8000
  ingress:
    enable: true
    host: authenticator.mw.local
    path: /
    tls:
      enable: true
  appconfig:
    host: 0.0.0.0
    port: 8000
    db_host: 192.168.0.11 #localhost
    db_port: 5432
    db_name: MWStackUsers
    db_user: postgres
    db_password: postgres
    enable_otel: true
