---
apiVersion: v2
name: mwstack-webhookforwarder
appVersion: "1.0"
description: "MWStack WebhookForwarder"
version: 1.1.0
type: application
dependencies:
  - name: deployment-template
    version: 0.1.0
    repository: https://matiwall.github.io/homelab.helm-charts/
    alias: deployment
