# my-react-app/values.yaml

global:
  name: mwstack-fittracker-frontend
deployment:
  replicaCount: 1
  image:
    repository: docker-registry.mw.local/fittracker-frontend
    tag: 20260301-103501-046d970



  service:
    name: fittracker-frontend
    targetPort: 8000
  ingress:
    enabled: true
    host: fittracker.mw.local
    path: /
    tls:
      enable: true
